spring.application.name=protospace-c

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/protospace
spring.datasource.username=sa
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

mybatis.configuration.map-underscore-to-camel-case=true

# Spring DevTool 設定
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# 本番環境では環境変数に入れる(これはローカル用のダミー)
app.jwt.secret=your-super-secret-key-that-is-very-long-and-secure-32-characters-minimum
app.jwt.expiration=86400000

# local限定
spring.flyway.clean-disabled=false

# 開発環境（localプロファイル）として起動する
spring.profiles.active=local

# CORS設定（本番環境等では環境変数等で上書き可能にする）
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}